[helpers]

[default]
depends = []

[default.files]
".config/ghostty" = "~/.config/ghostty"
".config/git" = "~/.config/git"
".config/tealdeer" = "~/.config/tealdeer"
".config/tmux" = "~/.config/tmux"
".config/vim" = "~/.config/vim"
".config/zsh" = "~/.config/zsh"
".config/starship.toml" = "~/.config/starship.toml"

[default.variables]

[settings]
default_target_type = "automatic"
