#:schema https://mise.jdx.dev/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ["node"]
lockfile = true
locked = false
experimental = true

[tools]
go = "1.26.0"
node = "24.13.1"
python = "3.14.1"
ruby = { compile = false, version = "4.0.1" }
rust = "1.91.1"
terraform = "1.14.3"
"aqua:abiosoft/colima" = "0.9.1"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:antonmedv/fx" = "39.2.0"
"aqua:aquasecurity/trivy" = "0.68.1"
"aqua:ast-grep/ast-grep" = "0.40.0"
"aqua:atuinsh/atuin" = "18.10.0"
"aqua:bootandy/dust" = "1.2.3"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:docker/buildx" = "0.30.1"
"aqua:docker/cli" = "29.1.2"
"aqua:docker/compose" = "5.0.0"
"aqua:duckdb/duckdb" = "1.4.2"
"aqua:helix-editor/helix" = "25.07.1"
"aqua:helm/helm" = "4.0.1"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:helmfile/vals" = "0.42.6"
"aqua:jesseduffield/lazygit" = "0.56.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:kubernetes/kubernetes/kubectl" = "1.34.2"
"aqua:lima-vm/lima" = "2.0.2"
"aqua:lsd-rs/lsd" = "1.2.0"
"aqua:muesli/duf" = "0.9.1"
"aqua:Orange-OpenSource/hurl" = "7.1.0"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:siketyan/ghr" = "0.4.5"
"aqua:starship/starship" = "1.24.1"
"aqua:SuperCuber/dotter" = "0.13.4"
"aqua:tealdeer-rs/tealdeer" = "1.8.1"
"aqua:terraform-linters/tflint" = "0.60.0"
"aqua:wagoodman/dive" = "0.13.1"
"aqua:Wilfred/difftastic" = "0.67.0"
"aqua:x-motemen/ghq" = "1.8.0"
"aqua:YS-L/csvlens" = "0.14.0"
"aqua:zellij-org/zellij" = "0.43.1"
"github:aquaproj/aqua" = "2.55.2"
"github:Canop/broot" = "1.53.0"
"github:wfxr/csview" = "1.3.4"
