#:schema https://mise.jdx.dev/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
go = "1.25.5"
node = "24.11.1"
terraform = "1.14.0"
ruby = "3.4.7"
python = "3.14.1"
rust = "1.91.1"
"aqua:ast-grep/ast-grep" = "0.40.0"
"aqua:atuinsh/atuin" = "18.10.0"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:abiosoft/colima" = "0.9.1"
"aqua:duckdb/duckdb" = "1.4.2"
"aqua:muesli/duf" = "0.9.1"
"aqua:bootandy/dust" = "1.2.3"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:antonmedv/fx" = "39.2.0"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:helix-editor/helix" = "25.07.1"
"aqua:Orange-OpenSource/hurl" = "7.1.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:starship/starship" = "1.24.1"
"aqua:tealdeer-rs/tealdeer" = "1.8.1"
"aqua:terraform-linters/tflint" = "0.60.0"
"aqua:aquasecurity/trivy" = "0.68.1"
"aqua:mikefarah/yq" = "4.49.2"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:wagoodman/dive" = "0.13.1"
"aqua:docker/cli" = "29.1.2"
"aqua:docker/buildx" = "0.30.1"
"aqua:docker/compose" = "5.0.0"
"aqua:Wilfred/difftastic" = "0.67.0"
"aqua:siketyan/ghr" = "0.4.5"
"aqua:BurntSushi/ripgrep" = "15.1.0"
